/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem);
void f_incref(void);
void f_decref(void);
casadi_int f_n_out(void);
casadi_int f_n_in(void);
const char* f_name_in(casadi_int i);
const char* f_name_out(casadi_int i);
const casadi_int* f_sparsity_in(casadi_int i);
const casadi_int* f_sparsity_out(casadi_int i);
int f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int g(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem);
void g_incref(void);
void g_decref(void);
casadi_int g_n_out(void);
casadi_int g_n_in(void);
const char* g_name_in(casadi_int i);
const char* g_name_out(casadi_int i);
const casadi_int* g_sparsity_in(casadi_int i);
const casadi_int* g_sparsity_out(casadi_int i);
int g_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
