/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) rocket_aero_moment_ ## ID
#endif

#include <math.h>
#include <casadi/mem.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};

casadi_real casadi_sq(casadi_real x) { return x*x;}

/* rocket_aero_moment:(x[14],u[4],p[15])->(MA_b[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a4, a5, a6, a7, a8, a9;
  a0=arg[2] ? arg[2][6] : 0;
  a1=arg[2] ? arg[2][8] : 0;
  a2=arg[2] ? arg[2][7] : 0;
  a3=1.0000000000000000e-03;
  a4=2.;
  a5=arg[0] ? arg[0][5] : 0;
  a6=arg[0] ? arg[0][6] : 0;
  a7=(a5*a6);
  a8=arg[0] ? arg[0][3] : 0;
  a9=arg[0] ? arg[0][4] : 0;
  a10=(a8*a9);
  a11=(a7-a10);
  a11=(a4*a11);
  a12=arg[0] ? arg[0][7] : 0;
  a11=(a11*a12);
  a13=casadi_sq(a8);
  a14=casadi_sq(a5);
  a15=(a13+a14);
  a16=casadi_sq(a9);
  a15=(a15-a16);
  a17=casadi_sq(a6);
  a15=(a15-a17);
  a18=arg[0] ? arg[0][8] : 0;
  a15=(a15*a18);
  a11=(a11+a15);
  a15=(a9*a5);
  a19=(a8*a6);
  a20=(a15+a19);
  a20=(a4*a20);
  a21=arg[0] ? arg[0][9] : 0;
  a20=(a20*a21);
  a11=(a11-a20);
  a20=fabs(a11);
  a20=(a3<a20);
  a9=(a9*a6);
  a8=(a8*a5);
  a5=(a9+a8);
  a5=(a4*a5);
  a5=(a5*a12);
  a15=(a15-a19);
  a15=(a4*a15);
  a15=(a15*a18);
  a5=(a5+a15);
  a15=(a13+a16);
  a15=(a15-a14);
  a15=(a15-a17);
  a15=(a15*a21);
  a5=(a5-a15);
  a15=fabs(a5);
  a15=(a3<a15);
  a20=(a20&&a15);
  a15=(a11/a5);
  a15=atan(a15);
  a15=(-a15);
  a20=(a20?a15:0);
  a15=arg[1] ? arg[1][1] : 0;
  a19=arg[1] ? arg[1][3] : 0;
  a6=(a15+a19);
  a20=(a20+a6);
  a20=(a2*a20);
  a6=(a1+a20);
  a22=5.0000000000000000e-01;
  a23=arg[2] ? arg[2][12] : 0;
  a22=(a22*a23);
  a23=casadi_sq(a5);
  a24=casadi_sq(a11);
  a23=(a23+a24);
  a13=(a13+a17);
  a13=(a13-a16);
  a13=(a13-a14);
  a13=(a13*a12);
  a7=(a7+a10);
  a7=(a4*a7);
  a7=(a7*a18);
  a13=(a13+a7);
  a9=(a9-a8);
  a4=(a4*a9);
  a4=(a4*a21);
  a13=(a13-a4);
  a4=casadi_sq(a13);
  a23=(a23+a4);
  a22=(a22*a23);
  a6=(a6*a22);
  a4=arg[2] ? arg[2][11] : 0;
  a6=(a6*a4);
  a23=sqrt(a23);
  a9=fabs(a23);
  a9=(a3<a9);
  a8=(a12/a23);
  a8=(a9?a8:0);
  a7=(!a9);
  a10=-1.;
  a7=(a7?a10:0);
  a8=(a8+a7);
  a7=(a18/a23);
  a14=(a9?a7:0);
  a14=casadi_sq(a14);
  a16=casadi_sq(a8);
  a14=(a14+a16);
  a14=sqrt(a14);
  a8=(a8/a14);
  a6=(a6*a8);
  a8=arg[2] ? arg[2][9] : 0;
  a14=arg[2] ? arg[2][10] : 0;
  a20=casadi_sq(a20);
  a20=(a14*a20);
  a20=(a8+a20);
  a20=(a20*a22);
  a20=(a20*a4);
  a7=(a7*a20);
  a7=(a9?a7:0);
  a6=(a6-a7);
  a7=(a0*a6);
  a16=fabs(a23);
  a16=(a3<a16);
  a17=(a18/a23);
  a24=(-a13);
  a24=fabs(a24);
  a24=(a3<a24);
  a25=fabs(a5);
  a25=(a3<a25);
  a24=(a24&&a25);
  a25=(a13/a5);
  a25=(-a25);
  a25=atan(a25);
  a25=(-a25);
  a24=(a24?a25:0);
  a25=arg[1] ? arg[1][2] : 0;
  a26=(a15+a25);
  a24=(a24+a26);
  a24=(a2*a24);
  a26=casadi_sq(a24);
  a26=(a14*a26);
  a26=(a8+a26);
  a26=(a26*a22);
  a26=(a26*a4);
  a17=(a17*a26);
  a17=(a16?a17:0);
  a6=(a6-a17);
  a17=(a0*a6);
  a7=(a7+a17);
  a17=(-a11);
  a17=fabs(a17);
  a17=(a3<a17);
  a27=fabs(a5);
  a27=(a3<a27);
  a17=(a17&&a27);
  a11=(a11/a5);
  a11=(-a11);
  a11=atan(a11);
  a11=(-a11);
  a17=(a17?a11:0);
  a19=(a15-a19);
  a17=(a17+a19);
  a17=(a2*a17);
  a19=(a1+a17);
  a19=(a19*a22);
  a19=(a19*a4);
  a11=fabs(a23);
  a11=(a3<a11);
  a27=(a12/a23);
  a27=(a11?a27:0);
  a28=(!a11);
  a28=(a28?a10:0);
  a27=(a27+a28);
  a28=(a18/a23);
  a29=(-a28);
  a29=(a11?a29:0);
  a29=casadi_sq(a29);
  a30=casadi_sq(a27);
  a29=(a29+a30);
  a29=sqrt(a29);
  a27=(a27/a29);
  a19=(a19*a27);
  a17=casadi_sq(a17);
  a17=(a14*a17);
  a17=(a8+a17);
  a17=(a17*a22);
  a17=(a17*a4);
  a28=(a28*a17);
  a28=(a11?a28:0);
  a19=(a19+a28);
  a6=(a6-a19);
  a19=(a0*a6);
  a7=(a7+a19);
  a19=fabs(a23);
  a19=(a3<a19);
  a18=(a18/a23);
  a28=fabs(a13);
  a28=(a3<a28);
  a27=fabs(a5);
  a3=(a3<a27);
  a28=(a28&&a3);
  a13=(a13/a5);
  a13=atan(a13);
  a13=(-a13);
  a28=(a28?a13:0);
  a15=(a15-a25);
  a28=(a28+a15);
  a2=(a2*a28);
  a28=casadi_sq(a2);
  a14=(a14*a28);
  a8=(a8+a14);
  a8=(a8*a22);
  a8=(a8*a4);
  a18=(a18*a8);
  a18=(a19?a18:0);
  a6=(a6-a18);
  a6=(a0*a6);
  a7=(a7+a6);
  if (res[0]!=0) res[0][0]=a7;
  a2=(a1+a2);
  a2=(a2*a22);
  a2=(a2*a4);
  a7=(a12/a23);
  a7=(a19?a7:0);
  a6=(!a19);
  a6=(a6?a10:0);
  a7=(a7+a6);
  a6=(a21/a23);
  a18=(-a6);
  a18=(a19?a18:0);
  a18=casadi_sq(a18);
  a14=casadi_sq(a7);
  a18=(a18+a14);
  a18=sqrt(a18);
  a7=(a7/a18);
  a2=(a2*a7);
  a6=(a6*a8);
  a19=(a19?a6:0);
  a2=(a2-a19);
  a19=(a21/a23);
  a19=(a19*a20);
  a20=(a9?a19:0);
  a1=(a1+a24);
  a1=(a1*a22);
  a1=(a1*a4);
  a12=(a12/a23);
  a12=(a16?a12:0);
  a4=(!a16);
  a4=(a4?a10:0);
  a12=(a12+a4);
  a4=(a21/a23);
  a10=(a16?a4:0);
  a10=casadi_sq(a10);
  a22=casadi_sq(a12);
  a10=(a10+a22);
  a10=sqrt(a10);
  a12=(a12/a10);
  a1=(a1*a12);
  a4=(a4*a26);
  a16=(a16?a4:0);
  a1=(a1+a16);
  a20=(a20+a1);
  a21=(a21/a23);
  a21=(a21*a17);
  a11=(a11?a21:0);
  a11=(a20+a11);
  a2=(a2-a11);
  a2=(a0*a2);
  a19=(a19*a0);
  a9=(a9?a19:0);
  a20=(a0*a20);
  a9=(a9+a20);
  a0=(a0*a11);
  a9=(a9+a0);
  a2=(a2-a9);
  if (res[0]!=0) res[0][1]=a2;
  a2=0.;
  if (res[0]!=0) res[0][2]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int rocket_aero_moment(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void rocket_aero_moment_incref(void) {
}

CASADI_SYMBOL_EXPORT void rocket_aero_moment_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rocket_aero_moment_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int rocket_aero_moment_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* rocket_aero_moment_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "u";
    case 2: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rocket_aero_moment_name_out(casadi_int i){
  switch (i) {
    case 0: return "MA_b";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rocket_aero_moment_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rocket_aero_moment_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rocket_aero_moment_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT casadi_functions* rocket_aero_moment_functions(void) {
  static casadi_functions fun = {
    rocket_aero_moment_incref,
    rocket_aero_moment_decref,
    rocket_aero_moment_n_in,
    rocket_aero_moment_n_out,
    rocket_aero_moment_name_in,
    rocket_aero_moment_name_out,
    rocket_aero_moment_sparsity_in,
    rocket_aero_moment_sparsity_out,
    rocket_aero_moment_work,
    rocket_aero_moment
  };
  return &fun;
}

#ifdef __cplusplus
} /* extern "C" */
#endif
