/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

#include <casadi/mem.h>
int double_this(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem);
void double_this_incref(void);
void double_this_decref(void);
casadi_int double_this_n_out(void);
casadi_int double_this_n_in(void);
const char* double_this_name_in(casadi_int i);
const char* double_this_name_out(casadi_int i);
const casadi_int* double_this_sparsity_in(casadi_int i);
const casadi_int* double_this_sparsity_out(casadi_int i);
int double_this_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
casadi_functions* double_this_functions(void);
#ifdef __cplusplus
} /* extern "C" */
#endif
