/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) casadi_gen_ ## ID
#endif

#include <math.h>
#include <casadi/mem.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};

/* double_this:(x[14],u[4],p[15])->(F_aero[3],F_prop[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0;
  a0=arg[2] ? arg[2][0] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[2] ? arg[2][1] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[2] ? arg[2][2] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[0] ? arg[0][3] : 0;
  if (res[1]!=0) res[1][0]=a0;
  a0=arg[0] ? arg[0][4] : 0;
  if (res[1]!=0) res[1][1]=a0;
  a0=arg[0] ? arg[0][5] : 0;
  if (res[1]!=0) res[1][2]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int double_this(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void double_this_incref(void) {
}

CASADI_SYMBOL_EXPORT void double_this_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int double_this_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int double_this_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* double_this_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "u";
    case 2: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* double_this_name_out(casadi_int i){
  switch (i) {
    case 0: return "F_aero";
    case 1: return "F_prop";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* double_this_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* double_this_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int double_this_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT casadi_functions* double_this_functions(void) {
  static casadi_functions fun = {
    double_this_incref,
    double_this_decref,
    double_this_n_in,
    double_this_n_out,
    double_this_name_in,
    double_this_name_out,
    double_this_sparsity_in,
    double_this_sparsity_out,
    double_this_work,
    double_this
  };
  return &fun;
}

#ifdef __cplusplus
} /* extern "C" */
#endif
