/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) fin_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

#include <casadi/mem.h>

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};

/* fins:(euler[3])->(fin_pos[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=9.9999999999999995e-08;
  a1=1.;
  a2=arg[0]? arg[0][0] : 0;
  a3=2.;
  a4=(a2/a3);
  a4=sin(a4);
  a5=arg[0]? arg[0][1] : 0;
  a6=(a5/a3);
  a6=cos(a6);
  a7=(a4*a6);
  a8=arg[0]? arg[0][2] : 0;
  a9=(a8/a3);
  a9=cos(a9);
  a7=(a7*a9);
  a2=(a2/a3);
  a2=cos(a2);
  a5=(a5/a3);
  a5=sin(a5);
  a10=(a2*a5);
  a8=(a8/a3);
  a8=sin(a8);
  a10=(a10*a8);
  a7=(a7-a10);
  a10=(a2*a6);
  a10=(a10*a9);
  a3=(a4*a5);
  a3=(a3*a8);
  a10=(a10+a3);
  a10=(a1+a10);
  a7=(a7/a10);
  a3=casadi_sq(a7);
  a11=(a2*a5);
  a11=(a11*a9);
  a12=(a4*a6);
  a12=(a12*a8);
  a11=(a11+a12);
  a11=(a11/a10);
  a12=casadi_sq(a11);
  a3=(a3+a12);
  a2=(a2*a6);
  a2=(a2*a8);
  a4=(a4*a5);
  a4=(a4*a9);
  a2=(a2-a4);
  a2=(a2/a10);
  a10=casadi_sq(a2);
  a3=(a3+a10);
  a3=sqrt(a3);
  a1=(a1<a3);
  a3=casadi_sq(a7);
  a10=casadi_sq(a11);
  a3=(a3+a10);
  a10=casadi_sq(a2);
  a3=(a3+a10);
  a10=(a7/a3);
  a10=(-a10);
  a10=(a1?a10:0);
  a4=(!a1);
  a7=(a4?a7:0);
  a10=(a10+a7);
  a7=casadi_sq(a10);
  a9=(a11/a3);
  a9=(-a9);
  a9=(a1?a9:0);
  a11=(a4?a11:0);
  a9=(a9+a11);
  a11=casadi_sq(a9);
  a7=(a7+a11);
  a3=(a2/a3);
  a3=(-a3);
  a1=(a1?a3:0);
  a4=(a4?a2:0);
  a1=(a1+a4);
  a4=casadi_sq(a1);
  a7=(a7+a4);
  a7=sqrt(a7);
  a0=(a0<a7);
  a4=4.;
  a2=atan(a7);
  a4=(a4*a2);
  a10=(a4*a10);
  a10=(a10/a7);
  a10=(-a10);
  a10=(a0?a10:0);
  if (res[0]!=0) res[0][0]=a10;
  a9=(a4*a9);
  a9=(a9/a7);
  a9=(-a9);
  a9=(a0?a9:0);
  if (res[0]!=0) res[0][1]=a9;
  a4=(a4*a1);
  a4=(a4/a7);
  a4=(-a4);
  a0=(a0?a4:0);
  if (res[0]!=0) res[0][2]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int fins(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int fins_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int fins_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fins_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int fins_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fins_release(int mem) {
}

CASADI_SYMBOL_EXPORT void fins_incref(void) {
}

CASADI_SYMBOL_EXPORT void fins_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int fins_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int fins_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real fins_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fins_name_in(casadi_int i){
  switch (i) {
    case 0: return "euler";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fins_name_out(casadi_int i){
  switch (i) {
    case 0: return "fin_pos";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fins_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fins_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int fins_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT casadi_functions* fins_functions(void) {
  static casadi_functions fun = {
    fins_incref,
    fins_decref,
    fins_checkout,
    fins_release,
    fins_default_in,
    fins_alloc_mem,
    fins_init_mem,
    fins_free_mem,
    fins_n_in,
    fins_n_out,
    fins_name_in,
    fins_name_out,
    fins_sparsity_in,
    fins_sparsity_out,
    fins_work,
    fins
  };
  return &fun;
}

#ifdef __cplusplus
} /* extern "C" */
#endif
