/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

#include <casadi/mem.h>
int fins(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int fins_alloc_mem(void);
int fins_init_mem(int mem);
void fins_free_mem(int mem);
int fins_checkout(void);
void fins_release(int mem);
void fins_incref(void);
void fins_decref(void);
casadi_int fins_n_out(void);
casadi_int fins_n_in(void);
casadi_real fins_default_in(casadi_int i);
const char* fins_name_in(casadi_int i);
const char* fins_name_out(casadi_int i);
const casadi_int* fins_sparsity_in(casadi_int i);
const casadi_int* fins_sparsity_out(casadi_int i);
int fins_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
casadi_functions* fins_functions(void);
#ifdef __cplusplus
} /* extern "C" */
#endif
